export class Patient{
Id:String;
Name:String;
FileNo:Number;
CitizenId:String;
Birthdate:Date;
Gender:String;
VIP:String;
Natinality:String;
PhoneNumber:String;
Email:String;
Country:String;
City:String;
Street:String;
Address1:String;
Address2:String;
ContactPerson:String;
ContactRelation:String;
ContactPhone:String;
Photo:String;
FirstVisitDate:Date;
RecordCreationDate:Date;
}